//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenVinos.Infraestructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Botella
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Botella()
        {
            this.Bodegas = new HashSet<Bodega>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Caducidad { get; set; }
        public Nullable<int> Añada { get; set; }
        public int IdVino { get; set; }
        public string Descripcion { get; set; }
        public bool Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bodega> Bodegas { get; set; }
        public virtual Vino Vino { get; set; }
    }
}
